service:
  extensions: [jaeger_storage, jaeger_query, healthcheckv2]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]
    
extensions:
  jaeger_query:
    storage:
      traces: some_storage
      traces_archive: another_store

  jaeger_storage:
    backends:
      some_storage:
         badger:
          directories:
            keys: "/data/jaeger/"
            values: "/data/jaeger/"
          ephemeral: false
      another_store:
        badger:
          directories:
            keys: "/data/jaeger_archive/"
            values: "/data/jaeger_archive/"
          ephemeral: false

  healthcheckv2:
    use_v2: true
    http:
      endpoint: "${env:JAEGER_LISTEN_HOST:-localhost}:13133"
    grpc:


receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "${env:JAEGER_LISTEN_HOST:-localhost}:4317"
      http:
        endpoint: "${env:JAEGER_LISTEN_HOST:-localhost}:4318"

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: some_storage