global:
  scrape_interval: 15s # как часто собираем метрики
  evaluation_interval: 15s # как часто выбираем правила
  scrape_timeout: 10s 

scrape_configs:
  - job_name: 'loyaltyhub'
    metrics_path: /metrics
    static_configs:
      - targets: ['loyaltyhub:8080']